# Generated by Django 3.0.5 on 2020-05-14 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('image', models.ImageField(default=None, upload_to='upload/img/tac')),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='project_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'project_categories',
            },
        ),
        migrations.CreateModel(
            name='project_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('contact', models.CharField(default=None, max_length=12)),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='students', to='tac.project', verbose_name='students')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('image', models.ImageField(default=None, upload_to='upload/img/tac')),
                ('details', models.TextField()),
                ('competetion_aim', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='team_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('contact', models.CharField(default=None, max_length=12)),
                ('team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='students', to='tac.team', verbose_name='students')),
            ],
        ),
        migrations.RemoveField(
            model_name='project_list',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project_students',
            name='project',
        ),
        migrations.RemoveField(
            model_name='team_students',
            name='team',
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'inventory_items'},
        ),
        migrations.AlterModelOptions(
            name='inventory_category',
            options={'verbose_name_plural': 'inventory_categories'},
        ),
        migrations.AlterModelOptions(
            name='tac_detail',
            options={'verbose_name_plural': 'details'},
        ),
        migrations.AlterModelOptions(
            name='tac_image',
            options={'verbose_name_plural': 'tac_images'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_id',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_type',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tac.inventory_category', verbose_name='item_type'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='inventory_category',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='contact_number',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='location_link',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='propose_your_project_link',
            field=models.URLField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='tagline',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='tac_image',
            name='photo',
            field=models.ImageField(default=None, upload_to='img/tac'),
        ),
        migrations.DeleteModel(
            name='project_categories',
        ),
        migrations.DeleteModel(
            name='project_list',
        ),
        migrations.DeleteModel(
            name='project_students',
        ),
        migrations.DeleteModel(
            name='team_students',
        ),
        migrations.DeleteModel(
            name='teams_list',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tac.project_category'),
        ),
    ]
