# Generated by Django 3.0.5 on 2020-04-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tac_head',
            name='contact',
            field=models.CharField(blank=True, default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='tac_head',
            name='email',
            field=models.CharField(blank=True, default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='tac_head',
            name='facebook',
            field=models.URLField(blank=True, default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='tac_head',
            name='git',
            field=models.URLField(blank=True, default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='tac_head',
            name='insta',
            field=models.URLField(blank=True, default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='tac_head',
            name='linkedin',
            field=models.URLField(blank=True, default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='tac_head',
            name='twitter',
            field=models.URLField(blank=True, default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='tac_head',
            name='youtube',
            field=models.URLField(blank=True, default='null', max_length=500),
        ),
    ]
