# Generated by Django 3.0.5 on 2020-04-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tac', '0002_auto_20200410_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=50)),
                ('item_id', models.CharField(default='null', max_length=100)),
                ('issue_allowed', models.BooleanField()),
                ('total_count', models.PositiveIntegerField()),
                ('min_reserve', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='guidelines',
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='issue_allowed',
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='min_reserve',
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='name',
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='total_count',
        ),
        migrations.RemoveField(
            model_name='tac_head',
            name='quote',
        ),
        migrations.AddField(
            model_name='facilities',
            name='about_facilites',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='facilities',
            name='guidelines',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='tac_head',
            name='location',
            field=models.CharField(blank=True, default='null', max_length=50),
        ),
    ]
