# Generated by Django 3.0.5 on 2020-05-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tac', '0002_auto_20200514_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_student',
            name='role',
            field=models.CharField(choices=[('Leader', 'Leader'), ('Member', 'Member')], default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team_student',
            name='role',
            field=models.CharField(choices=[('Leader', 'Leader'), ('Member', 'Member'), ('Manager', 'Manager')], default=True, max_length=10),
            preserve_default=False,
        ),
    ]
