# Generated by Django 3.0.5 on 2020-04-12 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tac', '0003_auto_20200412_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='item_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tac.inventory_category', verbose_name='students'),
        ),
    ]
