# Generated by Django 3.0.5 on 2020-05-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tac', '0004_auto_20200514_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tac_detail',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='tac_detail',
            name='git_link',
        ),
        migrations.RemoveField(
            model_name='tac_detail',
            name='insta_link',
        ),
        migrations.RemoveField(
            model_name='tac_detail',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='tac_detail',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='tac_detail',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='tac_detail',
            name='facebook',
            field=models.URLField(blank=True, null = True ,default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='tac_detail',
            name='git',
            field=models.URLField(blank=True, null = True ,default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='tac_detail',
            name='insta',
            field=models.URLField(blank=True, null = True ,default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='tac_detail',
            name='linkedin',
            field=models.URLField(blank=True, null = True ,default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='tac_detail',
            name='twitter',
            field=models.URLField(blank=True, null = True ,default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='tac_detail',
            name='youtube',
            field=models.URLField(blank=True, null = True ,default=None, max_length=500),
        ),
    ]
