# Generated by Django 3.0.5 on 2020-04-12 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tac', '0004_inventory_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tac.inventory_category', verbose_name='item_type'),
        ),
        migrations.AlterField(
            model_name='students',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='students', to='tac.project_list', verbose_name='students'),
        ),
    ]
