# Generated by Django 3.0.5 on 2020-05-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tac', '0005_auto_20200514_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tac_detail',
            name='facebook',
            field=models.URLField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='git',
            field=models.URLField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='insta',
            field=models.URLField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='linkedin',
            field=models.URLField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='twitter',
            field=models.URLField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='youtube',
            field=models.URLField(blank=True, default=None, max_length=500),
        ),
    ]
