# Generated by Django 3.0.5 on 2020-04-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tac', '0005_auto_20200412_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='min_reserve',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='total_count',
        ),
        migrations.AlterField(
            model_name='tac_head',
            name='facebook',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='tac_head',
            name='git',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='tac_head',
            name='insta',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='tac_head',
            name='linkedin',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='tac_head',
            name='twitter',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='tac_head',
            name='youtube',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
