# Generated by Django 3.0.5 on 2020-04-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tac', '0006_auto_20200412_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_id',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
