# Generated by Django 3.0.5 on 2020-05-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tac', '0007_auto_20200515_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tac_detail',
            old_name='location_link',
            new_name='location',
        ),
        migrations.AddField(
            model_name='team',
            name='team_photo',
            field=models.ImageField(default=None, upload_to='img/', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default=None, upload_to='img/', null=True),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='about_facilites',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='bigbook_bg_image',
            field=models.ImageField(default=None, upload_to='img/', null=True),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='guidelines',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='inventory_bg_image',
            field=models.ImageField(default=None, upload_to='img/', null=True),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='logo',
            field=models.ImageField(default=None, upload_to='img/', null=True),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='logo_black',
            field=models.ImageField(default=None, upload_to='img/', null=True),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='project_image',
            field=models.ImageField(default=None, upload_to='img/', null=True),
        ),
        migrations.AlterField(
            model_name='tac_image',
            name='photo',
            field=models.ImageField(default=None, upload_to='img/', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default=None, upload_to='img/', null=True),
        ),
    ]
