# Generated by Django 3.0.5 on 2020-04-12 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tac', '0007_auto_20200412_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tac_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=50)),
                ('about_tac', models.TextField()),
                ('tagline', models.CharField(default='null', max_length=100)),
                ('facebook_link', models.URLField(blank=True, max_length=500)),
                ('twitter_link', models.URLField(blank=True, max_length=500)),
                ('insta_link', models.URLField(blank=True, max_length=500)),
                ('git_link', models.URLField(blank=True, max_length=500)),
                ('linkedin_link', models.URLField(blank=True, max_length=500)),
                ('youtube_link', models.URLField(blank=True, max_length=500)),
                ('location_link', models.CharField(blank=True, default='null', max_length=50)),
                ('contact_number', models.CharField(blank=True, default='null', max_length=50)),
                ('email', models.CharField(blank=True, default='null', max_length=50)),
                ('guidelines', models.TextField(default='null')),
                ('about_facilites', models.TextField(default='null')),
                ('poject_content', models.TextField()),
                ('propose_your_project_link', models.URLField(default='null', max_length=500)),
                ('bigbook_content', models.TextField()),
                ('technical_teams_content', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='students',
            new_name='project_students',
        ),
        migrations.DeleteModel(
            name='bigbook',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='project',
        ),
        migrations.DeleteModel(
            name='facilities',
        ),
        migrations.DeleteModel(
            name='projects',
        ),
        migrations.DeleteModel(
            name='tac_head',
        ),
        migrations.DeleteModel(
            name='techteams',
        ),
        migrations.AddField(
            model_name='teams_list',
            name='competetion_aim',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='tac_image',
            name='photo',
            field=models.ImageField(default='null', upload_to='img/tac'),
        ),
        migrations.AlterField(
            model_name='team_students',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='students', to='tac.teams_list', verbose_name='students'),
        ),
        migrations.DeleteModel(
            name='categories',
        ),
        migrations.AddField(
            model_name='project_list',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tac.project_categories'),
        ),
    ]
