# Generated by Django 3.0.5 on 2020-04-12 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tac', '0008_auto_20200412_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tac_detail',
            old_name='poject_content',
            new_name='project_content',
        ),
    ]
