# Generated by Django 3.0.5 on 2020-05-17 11:55

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('tac', '0011_auto_20200517_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default=None, help_text='Aspect Ratio 4:3 for best results', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='img'),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='bigbook_bg_image',
            field=models.ImageField(default=None, help_text='Aspect Ratio 4:3 for best results', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='img'),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='inventory_bg_image',
            field=models.ImageField(default=None, help_text='Aspect Ratio 4:3 for best results', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='img'),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='logo',
            field=models.ImageField(default=None, help_text='Aspect Ratio 1:1 for best results', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='img'),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='logo_black',
            field=models.ImageField(default=None, help_text='Aspect Ratio 2:1 for best results', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='img'),
        ),
        migrations.AlterField(
            model_name='tac_detail',
            name='project_image',
            field=models.ImageField(default=None, help_text='Aspect Ratio 3:4 for best results', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='img'),
        ),
        migrations.AlterField(
            model_name='tac_image',
            name='photo',
            field=models.ImageField(default=None, help_text='Aspect Ratio 4:3 for best results', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='img'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default=None, help_text='Aspect Ratio 4:3 for best results', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='img'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_photo',
            field=models.ImageField(default=None, help_text='Aspect Ratio 4:3W for best results', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='img'),
        ),
    ]
