# Generated by Django 3.0.5 on 2020-05-08 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date of workshop')),
                ('presentation', models.URLField(default='null', max_length=500)),
                ('registration_form', models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='forms.Form')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'workshops',
            },
        ),
        migrations.CreateModel(
            name='highlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'highlights',
            },
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date event')),
                ('image', models.ImageField(upload_to='uploads')),
                ('date_registration_open', models.DateTimeField(auto_now_add=True, verbose_name='date of registration')),
                ('date_registration_close', models.DateTimeField(auto_now_add=True, verbose_name='date of registration close')),
                ('teamsize', models.IntegerField(default=1, verbose_name='max Team size')),
                ('refrences_link', models.URLField(default='null', max_length=500)),
                ('ps_link', models.URLField(default='null', max_length=500)),
                ('registration_form', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='forms.Form')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('about', models.TextField()),
                ('tagline', models.CharField(default=None, max_length=100)),
                ('quote', models.CharField(default=None, max_length=100)),
                ('logo_img', models.ImageField(default=None, upload_to='upload/img/')),
                ('facebook', models.URLField(blank=True, default=None, max_length=500)),
                ('twitter', models.URLField(blank=True, default=None, max_length=500)),
                ('insta', models.URLField(blank=True, default=None, max_length=500)),
                ('git', models.URLField(blank=True, default=None, max_length=500)),
                ('linkedin', models.URLField(blank=True, default=None, max_length=500)),
                ('youtube', models.URLField(blank=True, default=None, max_length=500)),
                ('club_room_location', models.CharField(default=None, max_length=50)),
                ('contact', models.CharField(default=None, max_length=50)),
                ('email', models.CharField(default=None, max_length=50)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'details',
            },
        ),
        migrations.CreateModel(
            name='about_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='null', upload_to='img/about')),
                ('club_name', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='about_images', to='clubs.details')),
            ],
            options={
                'verbose_name_plural': 'about_images',
            },
        ),
    ]
