# Generated by Django 3.0.5 on 2020-05-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='explore_bacground_img',
            field=models.ImageField(default=None,null=True, help_text='Aspect Ratio 7:3 for best restuls', upload_to='upload/img/'),
        ),
        migrations.AddField(
            model_name='details',
            name='logo_img_black',
            field=models.ImageField(default=None,null=True, help_text='Aspect Ratio 2:1 for best restuls', upload_to='upload/img/'),
        ),
        migrations.AddField(
            model_name='details',
            name='workshop_img',
            field=models.ImageField(default=None,null=True, help_text='Aspect Ratio 9:16 for best restuls', upload_to='upload/img/'),
        ),
        migrations.AlterField(
            model_name='about_images',
            name='photo',
            field=models.ImageField(default='null',null=True, help_text='Aspect Ratio 4:3 for best restuls', upload_to='img/about'),
        ),
        migrations.AlterField(
            model_name='details',
            name='logo_img',
            field=models.ImageField(default=None,null=True, help_text='Aspect Ratio 1:1 for best restuls', upload_to='upload/img/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(help_text='Aspect Ratio 4:3 for best restuls',null=True, upload_to='uploads'),
        ),
    ]
