# Generated by Django 3.0.5 on 2020-05-11 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20200511_0833'),
        ('clubs', '0002_auto_20200509_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_images',
            name='photo',
            field=models.ImageField(default='null', help_text='Aspect Ratio 4:3 for best restuls', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='details',
            name='explore_bacground_img',
            field=models.ImageField(default=None, help_text='Aspect Ratio 7:3 for best restuls', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='details',
            name='logo_img',
            field=models.ImageField(default=None, help_text='Aspect Ratio 1:1 for best restuls', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='details',
            name='logo_img_black',
            field=models.ImageField(default=None, help_text='Aspect Ratio 2:1 for best restuls', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='details',
            name='workshop_img',
            field=models.ImageField(default=None, help_text='Aspect Ratio 9:16 for best restuls', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(default=True, help_text='Aspect Ratio 4:3 for best restuls', upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='ps_link',
            field=models.URLField(blank=True, default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='events',
            name='refrences_link',
            field=models.URLField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='events',
            name='registration_form',
            field=models.ForeignKey(blank=True, default=None, help_text='The Basic Profile Information will be taken automatically on registratoin. Cretate a form only for extra info needed. Select a blank form if you do not need any other Details', on_delete=django.db.models.deletion.SET_DEFAULT, to='forms.Form'),
        ),
    ]
