# Generated by Django 2.2.6 on 2020-04-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20200404_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aero_calendar',
        ),
        migrations.AddField(
            model_name='aero_head',
            name='club_room_location',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='aero_head',
            name='contact',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='aero_head',
            name='email',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='aero_head',
            name='facebook',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='aero_head',
            name='git',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='aero_head',
            name='insta',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='aero_head',
            name='linkedin',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='aero_head',
            name='twitter',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='aero_head',
            name='youtube',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='aero_event',
            name='date_registration_close',
            field=models.DateTimeField(verbose_name='date of registration close'),
        ),
    ]
