# Generated by Django 3.0.5 on 2020-05-14 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20200512_1947'),
        ('clubs', '0003_auto_20200511_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='registration_form',
            field=models.OneToOneField(blank=True, default=None, help_text='The Basic Profile Information will be taken automatically on registratoin. Cretate a form only for extra info needed. Select a blank form if you do not need any other Details', on_delete=django.db.models.deletion.SET_DEFAULT, to='forms.Form'),
        ),
    ]
