# Generated by Django 3.0.5 on 2020-04-19 11:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0026_auto_20200419_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='null', upload_to='img/about')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'about_images',
            },
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('about', models.TextField()),
                ('tagline', models.CharField(default=None, max_length=100)),
                ('quote', models.CharField(default=None, max_length=100)),
                ('logo_img', models.ImageField(default=None, upload_to='upload/img/')),
                ('facebook', models.URLField(blank=True, default=None, max_length=500)),
                ('twitter', models.URLField(blank=True, default=None, max_length=500)),
                ('insta', models.URLField(blank=True, default=None, max_length=500)),
                ('git', models.URLField(blank=True, default=None, max_length=500)),
                ('linkedin', models.URLField(blank=True, default=None, max_length=500)),
                ('youtube', models.URLField(blank=True, default=None, max_length=500)),
                ('club_room_location', models.CharField(default=None, max_length=50)),
                ('contact', models.CharField(default=None, max_length=50)),
                ('email', models.CharField(default=None, max_length=50)),
                ('images', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='about_images', to='clubs.about_images')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'details',
            },
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date event')),
                ('image', models.ImageField(upload_to='uploads')),
                ('date_registration_open', models.DateTimeField(null=datetime.datetime(2020, 4, 19, 11, 42, 55, 99577), verbose_name='date of registration')),
                ('date_registration_close', models.DateTimeField(null=datetime.datetime(2020, 4, 19, 11, 42, 55, 99599), verbose_name='date of registration close')),
                ('teamsize', models.IntegerField(default=1, verbose_name='max Team size')),
                ('refrences_link', models.URLField(default='null', max_length=500)),
                ('ps_link', models.URLField(default='null', max_length=500)),
                ('registration_link', models.URLField(default='null', max_length=500)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='highlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'highlights',
            },
        ),
        migrations.CreateModel(
            name='workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date of workshop')),
                ('presentation', models.URLField(default='null', max_length=500)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'workshops',
            },
        ),
        migrations.DeleteModel(
            name='aero_about_image',
        ),
        migrations.DeleteModel(
            name='aero_event',
        ),
        migrations.DeleteModel(
            name='aero_head',
        ),
        migrations.DeleteModel(
            name='aero_highlight',
        ),
        migrations.DeleteModel(
            name='aero_workshop',
        ),
        migrations.AlterField(
            model_name='astro_event',
            name='date_registration_close',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 19, 11, 42, 55, 103653), verbose_name='date of registration close'),
        ),
        migrations.AlterField(
            model_name='astro_event',
            name='date_registration_open',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 19, 11, 42, 55, 103632), verbose_name='date of registration'),
        ),
        migrations.AlterField(
            model_name='biz_event',
            name='date_registration_close',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 19, 11, 42, 55, 116636), verbose_name='date of registration close'),
        ),
        migrations.AlterField(
            model_name='biz_event',
            name='date_registration_open',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 19, 11, 42, 55, 116614), verbose_name='date of registration'),
        ),
        migrations.AlterField(
            model_name='cops_event',
            name='date_registration_close',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 19, 11, 42, 55, 122022), verbose_name='date of registration close'),
        ),
        migrations.AlterField(
            model_name='cops_event',
            name='date_registration_open',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 19, 11, 42, 55, 122002), verbose_name='date of registration'),
        ),
        migrations.AlterField(
            model_name='csi_event',
            name='date_registration_close',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 19, 11, 42, 55, 119354), verbose_name='date of registration close'),
        ),
        migrations.AlterField(
            model_name='csi_event',
            name='date_registration_open',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 19, 11, 42, 55, 119335), verbose_name='date of registration'),
        ),
        migrations.AlterField(
            model_name='robo_event',
            name='date_registration_close',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 19, 11, 42, 55, 124637), verbose_name='date of registration close'),
        ),
        migrations.AlterField(
            model_name='robo_event',
            name='date_registration_open',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 19, 11, 42, 55, 124618), verbose_name='date of registration'),
        ),
        migrations.AlterField(
            model_name='sae_event',
            name='date_registration_close',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 19, 11, 42, 55, 127260), verbose_name='date of registration close'),
        ),
        migrations.AlterField(
            model_name='sae_event',
            name='date_registration_open',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 19, 11, 42, 55, 127240), verbose_name='date of registration'),
        ),
        migrations.DeleteModel(
            name='club_head',
        ),
    ]
