# Generated by Django 3.0.5 on 2020-04-19 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0028_auto_20200419_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_registration_close',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 13, 11, 15, 366581), verbose_name='date of registration close'),
        ),
        migrations.AlterField(
            model_name='events',
            name='date_registration_open',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 13, 11, 15, 366560), verbose_name='date of registration'),
        ),
    ]
