# Generated by Django 3.0.5 on 2020-04-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0029_auto_20200419_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_registration_close',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date of registration close'),
        ),
        migrations.AlterField(
            model_name='events',
            name='date_registration_open',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date of registration'),
        ),
    ]
