# Generated by Django 3.0.5 on 2020-05-07 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20200507_1326'),
        ('clubs', '0030_auto_20200419_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='registration_link',
        ),
        migrations.AddField(
            model_name='events',
            name='registration_form',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='forms.Form'),
        ),
        migrations.AddField(
            model_name='workshops',
            name='registration_form',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='forms.Form'),
        ),
    ]
