# Generated by Django 3.0.5 on 2020-05-07 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20200507_1356'),
        ('clubs', '0031_auto_20200507_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='about_image',
            field=models.ForeignKey(blank=True, null= True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='about_images', to='forms.Form'),
        ),
    ]
