# Generated by Django 3.0.5 on 2020-05-07 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0032_details_about_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='about_image',
        ),
        migrations.AddField(
            model_name='about_images',
            name='club_name',
            field=models.ForeignKey(blank=True, null=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='about_images', to='clubs.details'),
        ),
    ]
