# Generated by Django 3.0.5 on 2020-05-07 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InputFields', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forms.InputField')),
                ('SelectionFields', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forms.SelectionField')),
                ('UploadFields', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forms.UploadField')),
            ],
        ),
    ]
