# Generated by Django 3.0.5 on 2020-05-11 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fieldsets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('form', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='forms.Form')),
            ],
        ),
        migrations.AlterField(
            model_name='inputfield',
            name='form',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='forms.Fieldsets'),
        ),
        migrations.AlterField(
            model_name='selectionfield',
            name='form',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='forms.Fieldsets'),
        ),
        migrations.AlterField(
            model_name='uploadfield',
            name='form',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='forms.Fieldsets'),
        ),
    ]
