# Generated by Django 3.0.5 on 2020-05-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20200511_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputfield',
            name='Serialno',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selectionfield',
            name='Serialno',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadfield',
            name='Serialno',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
