# Generated by Django 3.0.5 on 2020-05-07 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='InputFields',
        ),
        migrations.RemoveField(
            model_name='form',
            name='SelectionFields',
        ),
        migrations.RemoveField(
            model_name='form',
            name='UploadFields',
        ),
        migrations.AddField(
            model_name='inputfield',
            name='form',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='forms.Form'),
        ),
        migrations.AddField(
            model_name='selectionfield',
            name='form',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='forms.Form'),
        ),
        migrations.AddField(
            model_name='uploadfield',
            name='form',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='forms.Form'),
        ),
    ]
