# Generated by Django 3.0.5 on 2020-05-11 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('forms', '0003_auto_20200511_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputfield',
            name='form',
        ),
        migrations.RemoveField(
            model_name='selectionfield',
            name='form',
        ),
        migrations.RemoveField(
            model_name='uploadfield',
            name='form',
        ),
        migrations.AddField(
            model_name='fieldsets',
            name='content_type',
            field=models.ForeignKey(blank=True,null=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='fieldsets',
            name='object_id',
            field=models.PositiveIntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fieldsets',
            name='form',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fieldsets', to='forms.Form'),
        ),
        migrations.AlterField(
            model_name='inputfield',
            name='type',
            field=models.CharField(choices=[('text', 'Text Small'), ('date', 'Date'), ('email', 'E-mail'), ('number', 'Number'), ('url', 'Link'), ('textarea', 'Text Large')], max_length=50),
        ),
        migrations.AlterField(
            model_name='selectionfield',
            name='type',
            field=models.CharField(choices=[('dropdown', 'Drop Down'), ('radio', 'Single Option'), ('checkbox', 'Multiple Option')], max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadfield',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('file', 'File')], max_length=50),
        ),
    ]
