# Generated by Django 3.0.5 on 2020-05-07 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0003_auto_20200507_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfield',
            old_name='uploadTo',
            new_name='uploadToURL',
        ),
        migrations.RemoveField(
            model_name='selectionfield',
            name='options',
        ),
        migrations.RemoveField(
            model_name='selectionfield',
            name='readOnly',
        ),
        migrations.RemoveField(
            model_name='uploadfield',
            name='readOnly',
        ),
        migrations.AddField(
            model_name='form',
            name='name',
            field=models.CharField(null=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='form',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='option',
            name='options',
            field=models.ForeignKey(default=None,null = True, on_delete=django.db.models.deletion.CASCADE, to='forms.SelectionField'),
        ),
        migrations.AlterField(
            model_name='inputfield',
            name='readOnly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inputfield',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
