# Generated by Django 3.0.5 on 2020-05-12 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20200511_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serialno', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('text', 'Text Small'), ('date', 'Date'), ('email', 'E-mail'), ('number', 'Number'), ('url', 'Link'), ('textarea', 'Text Large'), ('image', 'Image'), ('file', 'File'), ('dropdown', 'Drop Down'), ('radio', 'Single Option'), ('checkbox', 'Multiple Option')], max_length=50)),
                ('name', models.CharField(default=None, max_length=50)),
                ('default_value', models.CharField(blank=True, default=None, max_length=500)),
                ('placeholder_value', models.CharField(default=None, max_length=500)),
                ('required', models.BooleanField(default=False)),
                ('readOnly', models.BooleanField(default=False)),
                ('Validation_Error', models.CharField(default=None, max_length=100)),
                ('uploadToURL', models.URLField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Fieldset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('form', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fieldsets', to='forms.Form')),
            ],
        ),
        migrations.CreateModel(
            name='Selection_Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('value', models.CharField(default=None, max_length=50)),
                ('options', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Field')),
            ],
        ),
        migrations.RemoveField(
            model_name='fieldsets',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='fieldsets',
            name='form',
        ),
        migrations.DeleteModel(
            name='InputField',
        ),
        migrations.RemoveField(
            model_name='option',
            name='options',
        ),
        migrations.DeleteModel(
            name='UploadField',
        ),
        migrations.DeleteModel(
            name='Fieldsets',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='SelectionField',
        ),
        migrations.AddField(
            model_name='field',
            name='fieldset',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.Fieldset'),
        ),
    ]
