# Generated by Django 3.0.5 on 2020-05-07 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20200507_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='option',
            name='options',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forms.SelectionField'),
        ),
    ]
