# Generated by Django 3.0.5 on 2020-05-12 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20200512_0556'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Selection_Option',
            new_name='Option',
        ),
    ]
