# Generated by Django 3.0.5 on 2020-05-12 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20200512_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='fieldset',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.Form'),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Fieldset',
        ),
    ]
