# Generated by Django 2.2.6 on 2020-04-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aero_event',
            name='date_registration_open',
            field=models.DateTimeField(verbose_name='date of registration'),
        ),
    ]
