# Generated by Django 2.2.6 on 2020-04-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20200403_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aero_highlight',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aero_highlight',
            name='published_date',
        ),
    ]
