# Generated by Django 2.2.6 on 2020-04-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aero_about_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='null', upload_to='img/aero')),
            ],
        ),
        migrations.CreateModel(
            name='aero_calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(verbose_name='date start')),
                ('end_date', models.DateTimeField(verbose_name='date end')),
            ],
        ),
        migrations.CreateModel(
            name='aero_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date event')),
                ('image', models.ImageField(upload_to='uploads')),
                ('date_registration_open', models.DateTimeField(verbose_name='date of workshop')),
                ('date_registration_close', models.DateTimeField(verbose_name='date of workshop')),
                ('teamsize', models.IntegerField(default=1, verbose_name='max Team size')),
                ('refrences_link', models.URLField(default='null', max_length=500)),
                ('ps_link', models.URLField(default='null', max_length=500)),
                ('registration_link', models.URLField(default='null', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='aero_head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=50)),
                ('club_id', models.CharField(default='null', max_length=50)),
                ('about', models.TextField()),
                ('tagline', models.CharField(default='null', max_length=100)),
                ('logo_img', models.ImageField(default='null', upload_to='upload/img/aero')),
            ],
        ),
        migrations.CreateModel(
            name='aero_highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('published_date', models.DateTimeField(verbose_name='date published')),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='aero_workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date of workshop')),
                ('presentation', models.URLField(default='null', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='astro_calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(verbose_name='date start')),
                ('end_date', models.DateTimeField(verbose_name='date end')),
            ],
        ),
        migrations.CreateModel(
            name='astro_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date event')),
                ('image', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='astro_head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=50)),
                ('club_id', models.CharField(default='null', max_length=50)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='astro_highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('published_date', models.DateTimeField(verbose_name='date published')),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='astro_workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date of workshop')),
                ('presentation', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='biz_calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(verbose_name='date start')),
                ('end_date', models.DateTimeField(verbose_name='date end')),
            ],
        ),
        migrations.CreateModel(
            name='biz_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date event')),
                ('image', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='biz_head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=50)),
                ('club_id', models.CharField(default='null', max_length=50)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='biz_highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('published_date', models.DateTimeField(verbose_name='date published')),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='biz_workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date of workshop')),
                ('presentation', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='cops_calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(verbose_name='date start')),
                ('end_date', models.DateTimeField(verbose_name='date end')),
            ],
        ),
        migrations.CreateModel(
            name='cops_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date event')),
                ('image', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='cops_head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=50)),
                ('club_id', models.CharField(default='null', max_length=50)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='cops_highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('published_date', models.DateTimeField(verbose_name='date published')),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='cops_workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date of workshop')),
                ('presentation', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='csi_calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(verbose_name='date start')),
                ('end_date', models.DateTimeField(verbose_name='date end')),
            ],
        ),
        migrations.CreateModel(
            name='csi_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date event')),
                ('image', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='csi_head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=50)),
                ('club_id', models.CharField(default='null', max_length=50)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='csi_highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('published_date', models.DateTimeField(verbose_name='date published')),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='csi_workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date of workshop')),
                ('presentation', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='robo_calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(verbose_name='date start')),
                ('end_date', models.DateTimeField(verbose_name='date end')),
            ],
        ),
        migrations.CreateModel(
            name='robo_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date event')),
                ('image', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='robo_head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=50)),
                ('club_id', models.CharField(default='null', max_length=50)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='robo_highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('published_date', models.DateTimeField(verbose_name='date published')),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='robo_workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date of workshop')),
                ('presentation', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='sae_calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(verbose_name='date start')),
                ('end_date', models.DateTimeField(verbose_name='date end')),
            ],
        ),
        migrations.CreateModel(
            name='sae_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date event')),
                ('image', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='sae_head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=50)),
                ('club_id', models.CharField(default='null', max_length=50)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='sae_highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('published_date', models.DateTimeField(verbose_name='date published')),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='sae_workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date of workshop')),
                ('presentation', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
