# Generated by Django 2.2.6 on 2020-04-05 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20200405_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='astro_about_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='null', upload_to='img/astro')),
            ],
        ),
        migrations.CreateModel(
            name='biz_about_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='null', upload_to='img/biz')),
            ],
        ),
        migrations.CreateModel(
            name='cops_about_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='null', upload_to='img/cops')),
            ],
        ),
        migrations.CreateModel(
            name='csi_about_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='null', upload_to='img/csi')),
            ],
        ),
        migrations.CreateModel(
            name='robo_about_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='null', upload_to='img/robo')),
            ],
        ),
        migrations.CreateModel(
            name='sae_about_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='null', upload_to='img/sae')),
            ],
        ),
        migrations.DeleteModel(
            name='astro_calendar',
        ),
        migrations.DeleteModel(
            name='biz_calendar',
        ),
        migrations.DeleteModel(
            name='cops_calendar',
        ),
        migrations.DeleteModel(
            name='csi_calendar',
        ),
        migrations.DeleteModel(
            name='robo_calendar',
        ),
        migrations.DeleteModel(
            name='sae_calendar',
        ),
        migrations.RemoveField(
            model_name='astro_highlight',
            name='image',
        ),
        migrations.RemoveField(
            model_name='astro_highlight',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='biz_highlight',
            name='image',
        ),
        migrations.RemoveField(
            model_name='biz_highlight',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='cops_highlight',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cops_highlight',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='csi_highlight',
            name='image',
        ),
        migrations.RemoveField(
            model_name='csi_highlight',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='robo_highlight',
            name='image',
        ),
        migrations.RemoveField(
            model_name='robo_highlight',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='sae_highlight',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sae_highlight',
            name='published_date',
        ),
        migrations.AddField(
            model_name='astro_event',
            name='date_registration_close',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 5, 4, 59, 24, 15212), verbose_name='date of registration close'),
            preserve_default=datetime.datetime(2020, 4, 5, 4, 59, 24, 15212),
        ),
        migrations.AddField(
            model_name='astro_event',
            name='date_registration_open',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 5, 4, 59, 24, 15185), verbose_name='date of registration'),
            preserve_default=datetime.datetime(2020, 4, 5, 4, 59, 24, 15185),
        ),
        migrations.AddField(
            model_name='astro_event',
            name='ps_link',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='astro_event',
            name='refrences_link',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='astro_event',
            name='registration_link',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='astro_event',
            name='teamsize',
            field=models.IntegerField(default=1, verbose_name='max Team size'),
        ),
        migrations.AddField(
            model_name='astro_head',
            name='club_room_location',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='astro_head',
            name='contact',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='astro_head',
            name='email',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='astro_head',
            name='facebook',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='astro_head',
            name='git',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='astro_head',
            name='insta',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='astro_head',
            name='linkedin',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='astro_head',
            name='logo_img',
            field=models.ImageField(default='null', upload_to='upload/img/astro'),
        ),
        migrations.AddField(
            model_name='astro_head',
            name='tagline',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='astro_head',
            name='twitter',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='astro_head',
            name='youtube',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='biz_event',
            name='date_registration_close',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 5, 4, 59, 24, 18041), verbose_name='date of registration close'),
            preserve_default=datetime.datetime(2020, 4, 5, 4, 59, 24, 18041),
        ),
        migrations.AddField(
            model_name='biz_event',
            name='date_registration_open',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 5, 4, 59, 24, 18017), verbose_name='date of registration'),
            preserve_default=datetime.datetime(2020, 4, 5, 4, 59, 24, 18017),
        ),
        migrations.AddField(
            model_name='biz_event',
            name='ps_link',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='biz_event',
            name='refrences_link',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='biz_event',
            name='registration_link',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='biz_event',
            name='teamsize',
            field=models.IntegerField(default=1, verbose_name='max Team size'),
        ),
        migrations.AddField(
            model_name='biz_head',
            name='club_room_location',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='biz_head',
            name='contact',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='biz_head',
            name='email',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='biz_head',
            name='facebook',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='biz_head',
            name='git',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='biz_head',
            name='insta',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='biz_head',
            name='linkedin',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='biz_head',
            name='logo_img',
            field=models.ImageField(default='null', upload_to='upload/img/biz'),
        ),
        migrations.AddField(
            model_name='biz_head',
            name='tagline',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='biz_head',
            name='twitter',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='biz_head',
            name='youtube',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='cops_event',
            name='date_registration_close',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 5, 4, 59, 24, 24835), verbose_name='date of registration close'),
            preserve_default=datetime.datetime(2020, 4, 5, 4, 59, 24, 24835),
        ),
        migrations.AddField(
            model_name='cops_event',
            name='date_registration_open',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 5, 4, 59, 24, 24778), verbose_name='date of registration'),
            preserve_default=datetime.datetime(2020, 4, 5, 4, 59, 24, 24778),
        ),
        migrations.AddField(
            model_name='cops_event',
            name='ps_link',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='cops_event',
            name='refrences_link',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='cops_event',
            name='registration_link',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='cops_event',
            name='teamsize',
            field=models.IntegerField(default=1, verbose_name='max Team size'),
        ),
        migrations.AddField(
            model_name='cops_head',
            name='club_room_location',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='cops_head',
            name='contact',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='cops_head',
            name='email',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='cops_head',
            name='facebook',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='cops_head',
            name='git',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='cops_head',
            name='insta',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='cops_head',
            name='linkedin',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='cops_head',
            name='logo_img',
            field=models.ImageField(default='null', upload_to='upload/img/cops'),
        ),
        migrations.AddField(
            model_name='cops_head',
            name='tagline',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='cops_head',
            name='twitter',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='cops_head',
            name='youtube',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='csi_event',
            name='date_registration_close',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 5, 4, 59, 24, 20865), verbose_name='date of registration close'),
            preserve_default=datetime.datetime(2020, 4, 5, 4, 59, 24, 20865),
        ),
        migrations.AddField(
            model_name='csi_event',
            name='date_registration_open',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 5, 4, 59, 24, 20837), verbose_name='date of registration'),
            preserve_default=datetime.datetime(2020, 4, 5, 4, 59, 24, 20837),
        ),
        migrations.AddField(
            model_name='csi_event',
            name='ps_link',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='csi_event',
            name='refrences_link',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='csi_event',
            name='registration_link',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='csi_event',
            name='teamsize',
            field=models.IntegerField(default=1, verbose_name='max Team size'),
        ),
        migrations.AddField(
            model_name='csi_head',
            name='club_room_location',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='csi_head',
            name='contact',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='csi_head',
            name='email',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='csi_head',
            name='facebook',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='csi_head',
            name='git',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='csi_head',
            name='insta',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='csi_head',
            name='linkedin',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='csi_head',
            name='logo_img',
            field=models.ImageField(default='null', upload_to='upload/img/csi'),
        ),
        migrations.AddField(
            model_name='csi_head',
            name='tagline',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='csi_head',
            name='twitter',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='csi_head',
            name='youtube',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='robo_event',
            name='date_registration_close',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 5, 4, 59, 24, 29194), verbose_name='date of registration close'),
            preserve_default=datetime.datetime(2020, 4, 5, 4, 59, 24, 29194),
        ),
        migrations.AddField(
            model_name='robo_event',
            name='date_registration_open',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 5, 4, 59, 24, 29166), verbose_name='date of registration'),
            preserve_default=datetime.datetime(2020, 4, 5, 4, 59, 24, 29166),
        ),
        migrations.AddField(
            model_name='robo_event',
            name='ps_link',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='robo_event',
            name='refrences_link',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='robo_event',
            name='registration_link',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='robo_event',
            name='teamsize',
            field=models.IntegerField(default=1, verbose_name='max Team size'),
        ),
        migrations.AddField(
            model_name='robo_head',
            name='club_room_location',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='robo_head',
            name='contact',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='robo_head',
            name='email',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='robo_head',
            name='facebook',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='robo_head',
            name='git',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='robo_head',
            name='insta',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='robo_head',
            name='linkedin',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='robo_head',
            name='logo_img',
            field=models.ImageField(default='null', upload_to='upload/img/robo'),
        ),
        migrations.AddField(
            model_name='robo_head',
            name='tagline',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='robo_head',
            name='twitter',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='robo_head',
            name='youtube',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='sae_event',
            name='date_registration_close',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 5, 4, 59, 24, 32248), verbose_name='date of registration close'),
            preserve_default=datetime.datetime(2020, 4, 5, 4, 59, 24, 32248),
        ),
        migrations.AddField(
            model_name='sae_event',
            name='date_registration_open',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 5, 4, 59, 24, 32223), verbose_name='date of registration'),
            preserve_default=datetime.datetime(2020, 4, 5, 4, 59, 24, 32223),
        ),
        migrations.AddField(
            model_name='sae_event',
            name='ps_link',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='sae_event',
            name='refrences_link',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='sae_event',
            name='registration_link',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='sae_event',
            name='teamsize',
            field=models.IntegerField(default=1, verbose_name='max Team size'),
        ),
        migrations.AddField(
            model_name='sae_head',
            name='club_room_location',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='sae_head',
            name='contact',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='sae_head',
            name='email',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='sae_head',
            name='facebook',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='sae_head',
            name='git',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='sae_head',
            name='insta',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='sae_head',
            name='linkedin',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='sae_head',
            name='logo_img',
            field=models.ImageField(default='null', upload_to='upload/img/sae'),
        ),
        migrations.AddField(
            model_name='sae_head',
            name='tagline',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='sae_head',
            name='twitter',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='sae_head',
            name='youtube',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='aero_event',
            name='date_registration_close',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 5, 4, 59, 24, 11904), verbose_name='date of registration close'),
        ),
        migrations.AlterField(
            model_name='aero_event',
            name='date_registration_open',
            field=models.DateTimeField(null=datetime.datetime(2020, 4, 5, 4, 59, 24, 11872), verbose_name='date of registration'),
        ),
        migrations.AlterField(
            model_name='astro_workshop',
            name='presentation',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='biz_workshop',
            name='presentation',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='cops_workshop',
            name='presentation',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='csi_workshop',
            name='presentation',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='robo_workshop',
            name='presentation',
            field=models.URLField(default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='sae_workshop',
            name='presentation',
            field=models.URLField(default='null', max_length=500),
        ),
    ]
